from enum import StrEnum, auto


class HeroesEnum(StrEnum):
    """All heroes."""

    @staticmethod
    def _generate_next_value_(name, start, count, last_values):
        return name.replace("_and_", " & ").replace("_", " ")

    @classmethod
    def _missing_(cls, value: object) -> "HeroesEnum | None":
        """Accept names this enum used to spell wrongly.

        `excluded_heroes` in a saved profile is `list[HeroesEnum]`, so a stored value
        that no longer matches a member does not degrade - the whole settings load
        fails validation and the user loses every exclusion they had set.

        Three names were corrected against the wiki's playable hero list on 2026-09-06.
        Anyone who had excluded one of them has it written in their profile under the
        old spelling, so the old spellings must keep resolving. New profiles are written
        with the corrected values.
        """
        renamed = {
            "Isabelle": cls.Isabella,
            "Smokey": cls.Smokey_and_Meerky,
            "Sylphyra": cls.Sylphira,
        }
        return renamed.get(value) if isinstance(value, str) else None

    Aliceth = auto()
    Alna = auto()
    Alsa = auto()
    Antandra = auto()
    Arden = auto()
    Atalanta = auto()
    Athalia = auto()
    Aurora = auto()
    Baelran = auto()
    Berial = auto()
    Bonnie = auto()
    Brutus = auto()
    Bryon = auto()
    Callan = auto()
    Carolina = auto()
    Cassadee = auto()
    Cecia = auto()
    Contess = auto()
    Cryonaia = auto()
    Cyran = auto()
    Daimon = auto()
    Damian = auto()
    Dionel = auto()
    Dunlingr = auto()
    Eironn = auto()
    Elijah_and_Lailah = auto()
    Evie = auto()
    Fay = auto()
    Frieren = auto()
    Faramor = auto()
    Florabelle = auto()
    Galahad = auto()
    Gerda = auto()
    Granny_Dahnie = auto()
    Gunnar = auto()
    Gwyneth = auto()
    Harak = auto()
    Hepler = auto()
    Hewynn = auto()
    Himmel = auto()
    Hodgkin = auto()
    Hugin = auto()
    Igor = auto()
    Indris = auto()
    Isabella = auto()
    Kafra = auto()
    Kazim = auto()
    Koko = auto()
    Kordan = auto()
    Korin = auto()
    Kruger = auto()
    Kulu = auto()
    Laios = auto()
    Lamentis = auto()
    Lenya = auto()
    Lily_May = auto()
    Lorsan = auto()
    Lucca = auto()
    Lucius = auto()
    Lucy = auto()
    Ludovic = auto()
    Lumont = auto()
    Lyca = auto()
    Marcille = auto()
    Marilee = auto()
    Mehira = auto()
    Mikola = auto()
    Mirael = auto()
    Nara = auto()
    Natsu = auto()
    Nazrik = auto()
    Nerion = auto()
    Niru = auto()
    Odie = auto()
    Pandora = auto()
    Pang = auto()
    Parisa = auto()
    Peggy = auto()
    Perseus = auto()
    Phraesto = auto()
    Pippa = auto()
    Ravion = auto()
    Reinier = auto()
    Rhys = auto()
    Rowan = auto()
    Saida = auto()
    Salazer = auto()
    Satrana = auto()
    Scarlita = auto()
    Seth = auto()
    Shadewing = auto()
    Shakir = auto()
    Shemira = auto()
    Silven = auto()
    Silvina = auto()
    Sinbad = auto()
    Smokey_and_Meerky = auto()
    Solise = auto()
    Sonja = auto()
    Soren = auto()
    Sylphira = auto()
    Talene = auto()
    Tasi = auto()
    Temesia = auto()
    Thador = auto()
    Thoran = auto()
    Tilaya = auto()
    Ulmus = auto()
    Vala = auto()
    Valen = auto()
    Valka = auto()
    Velara = auto()
    Viperian = auto()
    Walker = auto()
    Zandrok = auto()
    Zanie = auto()
    Zorya = auto()
    Hammie = auto()
    Chippy = auto()
    Orion = auto()
    Rolan = auto()
    Voracia = auto()
    Taichi_and_Agumon = auto()
    Yamato_and_Gabumon = auto()
    Eryndor = auto()
