#!/usr/bin/env python3
"""Rebuild the AFK Journey hero + Solstice Clash database from the Fandom wiki API.

Everything in this directory is generated by this script. Re-run it to refresh
after a balance patch or a new event rotation:

    python3 build_hero_db.py

Why the API and not the HTML: the wiki's normal pages sit behind Cloudflare
(WebFetch gets HTTP 402, agent-browser gets a "Just a moment..." challenge), but
`api.php` is not protected. No stealth browser is needed.

Why this data is trustworthy for template matching: the wiki's `File:Hero <Name>.png`
files are the datamined in-game combat icons. Rendering the in-game 96px circular
roster icon from them is a fixed transform (see ICON_SCALE / ICON_OFFSET below),
verified at 20/20 on hand-labelled Lightbearer icons and 8/8 against a 124-hero
candidate set.

Outputs (all committed):
    heroes.sqlite            hero / hero_skill / hero_skin / solstice_roster
    hero_db_full.json        parsed hero records incl. skills
    wiki_skins.json          skin -> {hero, rarity, type}
    wiki_skins_by_hero.json  hero -> [skin names]
    solstice_roster.json     event usable/banned lists with stat adjustments
    solstice_clash_wiki.txt  raw wikitext snapshot of the event page
"""

from __future__ import annotations

import json
import os
import re
import sqlite3
import time
import urllib.parse
import urllib.request
from collections import Counter

API = "https://afk-journey.fandom.com/api.php"
UA = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) Chrome/146.0 Safari/537.36"}
HERE = os.path.dirname(os.path.abspath(__file__))

EVENT_PAGE = "Solstice Clash"
FACTIONS = ["Lightbearer", "Mauler", "Wilder", "Graveborn",
            "Hypogean", "Celestial", "Dimensional"]

# Transform from a wiki combat icon (180x248) to the in-game 96px circular icon.
ICON_SCALE = 0.68
ICON_OFFSET = (13, 35)   # (x, y) crop origin after scaling
ICON_MASK_RADIUS = 44


def api(**params):
    params.setdefault("format", "json")
    params.setdefault("formatversion", "2")
    req = urllib.request.Request(API + "?" + urllib.parse.urlencode(params), headers=UA)
    return json.load(urllib.request.urlopen(req, timeout=60))


def category_members(title: str) -> list[str]:
    out, cont = [], {}
    while True:
        d = api(action="query", list="categorymembers", cmtitle=title,
                cmlimit="500", **cont)
        out += [m["title"] for m in d["query"]["categorymembers"]
                if not m["title"].startswith(("Category:", "File:", "Template:"))]
        if "continue" not in d:
            return out
        cont = d["continue"]


def wikitext_for(titles: list[str], batch: int = 50) -> dict[str, str]:
    out = {}
    for i in range(0, len(titles), batch):
        d = api(action="query", titles="|".join(titles[i:i + batch]),
                prop="revisions", rvprop="content", rvslots="main")
        for pg in d["query"]["pages"]:
            try:
                out[pg["title"]] = pg["revisions"][0]["slots"]["main"]["content"]
            except (KeyError, IndexError):
                continue
        time.sleep(0.2)
    return out


def templates(wt: str, name: str) -> list[str]:
    """Extract {{name ...}} blocks, brace-balanced so nested templates survive."""
    out, i, tag = [], 0, "{{" + name
    while True:
        i = wt.find(tag, i)
        if i < 0:
            return out
        j, depth = i + 2, 1
        while j < len(wt) and depth:
            if wt.startswith("{{", j):
                depth += 1
                j += 2
            elif wt.startswith("}}", j):
                depth -= 1
                j += 2
            else:
                j += 1
        out.append(wt[i + 2:j - 2])
        i = j


def fields(block: str) -> dict[str, str]:
    """Split a template body on top-level pipes only."""
    parts, depth, cur = [], 0, ""
    for k, c in enumerate(block):
        if block.startswith("{{", k) or block.startswith("[[", k):
            depth += 1
        if block.startswith("}}", k) or block.startswith("]]", k):
            depth = max(0, depth - 1)
        if c == "|" and depth == 0:
            parts.append(cur)
            cur = ""
        else:
            cur += c
    parts.append(cur)
    out = {}
    for p in parts[1:]:
        if "=" in p:
            k, v = p.split("=", 1)
            out[k.strip()] = v.strip()
    return out


def clean(s: str | None) -> str | None:
    if not s:
        return s
    s = re.sub(r"\{\{b\|([^}]*)\}\}", r"\1", s)
    s = re.sub(r"\{\{ATK\|([^}|]*)[^}]*\}\}", r"ATK \1", s)
    s = re.sub(r"\{\{PWR\|([^}|]*)[^}]*\}\}", r"PWR \1", s)
    s = re.sub(r"\{\{[^}]*\}\}", "", s)
    s = re.sub(r"\[\[([^\]|]*\|)?([^\]]*)\]\]", r"\2", s)
    return re.sub(r"\s+", " ", s).strip()


def slugify(name: str) -> str:
    return re.sub(r"_+", "_", re.sub(r"[^a-z0-9]", "_", name.lower())).strip("_")


def build_skins() -> dict[str, dict]:
    pages = category_members("Category:Skins")
    res = {}
    for title, wt in wikitext_for(pages).items():
        def fld(n):
            m = re.search(r"\|\s*" + n + r"\s*=\s*([^\n|]+)", wt)
            return m.group(1).strip() if m else None
        res[title] = {"hero": fld("hero"), "rarity": fld("rarity"), "type": fld("type")}
    return res


def build_heroes(skins_by_hero: dict[str, list[str]]) -> list[dict]:
    pages = category_members("Category:Heroes")
    out = []
    for name, wt in wikitext_for(pages).items():
        ib = templates(wt, "Character Infobox")
        if not ib:
            continue
        f = fields("x|" + ib[0])
        skills, seen = [], set()
        for marker in ("Skill\n", "Skill|", "Skill "):
            for b in templates(wt, marker):
                g = fields("x|" + b)
                nm = g.get("name")
                if not nm or nm in seen:
                    continue
                seen.add(nm)
                skills.append({
                    "type": g.get("type"), "name": nm, "range": g.get("range"),
                    "cd": g.get("cd"), "energy": g.get("energy"),
                    "lite": clean(g.get("lite")), "full": clean(g.get("full")),
                })
        faction = f.get("faction")
        if faction and faction.startswith("<!--"):
            faction = "Lightbearer"      # wiki comment marks a factionless Lightbearer
        rng = f.get("range")
        out.append({
            "name": name, "slug": slugify(name), "faction": faction,
            "hero_class": f.get("class"), "damage_type": f.get("damage"),
            "attack_range": (re.sub(r"[^0-9]", "", rng) or None) if rng else None,
            "rarity": f.get("rarity"), "title": f.get("title"),
            "gender": f.get("gender"), "race": f.get("race"),
            "skins": skins_by_hero.get(name, []), "skills": skills,
        })
    return out


def build_event_roster(wt: str) -> tuple[list[dict], list[str]]:
    i, j = wt.find("==Usable Heroes=="), wt.find("==Banned Heroes==")
    usable = []
    parts = re.split(r"\{\{(" + "|".join(FACTIONS) + r")\}\}", wt[i:j])
    for k in range(1, len(parts), 2):
        faction, body = parts[k], parts[k + 1]
        m = (re.search(r"\{\{Card List\|mini=1\|param_delim=,\|1=(.*?)\}\}", body, re.S)
             or re.search(r"\{\{Card List\|mini=1\|(.*?)\}\}", body, re.S))
        if not m:
            continue
        raw = re.sub(r"<!--.*?-->", "", m.group(1), flags=re.S)
        for ent in raw.split(";"):
            ent = ent.strip()
            if not ent:
                continue
            cm = re.search(r"\{caption=(.*?)\}", ent)
            adj = cm.group(1).strip() if cm else ""
            nm = re.sub(r"\{caption=.*?\}", "", ent).strip()
            if not nm:
                continue
            hp = atk = None
            for pm in re.finditer(r"(HP|ATK)\s*([+-]\d+)%", adj):
                if pm.group(1) == "HP":
                    hp = int(pm.group(2))
                else:
                    atk = int(pm.group(2))
            usable.append({"faction": faction, "name": nm, "adjustment": adj,
                           "hp_pct": hp, "atk_pct": atk})
    bm = re.search(r"\{\{Card List\|mini=1\|(.*?)\}\}", wt[j:], re.S)
    banned = [b.strip() for b in
              re.sub(r"<!--.*?-->", "", bm.group(1), flags=re.S).split(";") if b.strip()]
    return usable, banned


SCHEMA = """
CREATE TABLE hero(
  slug TEXT PRIMARY KEY, name TEXT NOT NULL, faction TEXT, hero_class TEXT,
  damage_type TEXT, attack_range INTEGER, rarity TEXT, title TEXT,
  gender TEXT, race TEXT, combat_icon TEXT);
CREATE TABLE hero_skin(
  id INTEGER PRIMARY KEY, hero_slug TEXT NOT NULL REFERENCES hero(slug),
  skin_name TEXT NOT NULL, combat_icon TEXT, UNIQUE(hero_slug, skin_name));
CREATE TABLE hero_skill(
  id INTEGER PRIMARY KEY, hero_slug TEXT NOT NULL REFERENCES hero(slug),
  skill_type TEXT, skill_name TEXT, attack_range TEXT, cooldown TEXT,
  energy TEXT, summary TEXT, detail TEXT, UNIQUE(hero_slug, skill_name));
CREATE TABLE solstice_roster(
  id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, hero_slug TEXT, faction TEXT,
  status TEXT NOT NULL, adjustment TEXT, hp_pct INTEGER, atk_pct INTEGER);
CREATE INDEX idx_hero_faction ON hero(faction);
CREATE INDEX idx_skill_hero ON hero_skill(hero_slug);
CREATE INDEX idx_roster_status ON solstice_roster(status);
"""


def main() -> None:
    print("fetching skins ...")
    skins = build_skins()
    by_hero: dict[str, list[str]] = {}
    for skin, v in skins.items():
        if v.get("hero"):
            by_hero.setdefault(v["hero"], []).append(skin)

    print("fetching heroes ...")
    heroes = build_heroes(by_hero)

    print(f"fetching event page {EVENT_PAGE!r} ...")
    event_wt = api(action="parse", page=EVENT_PAGE, prop="wikitext")["parse"]["wikitext"]
    usable, banned = build_event_roster(event_wt)

    for fn, data in (("hero_db_full.json", heroes),
                     ("wiki_skins.json", skins),
                     ("wiki_skins_by_hero.json", by_hero),
                     ("solstice_roster.json", {"usable": usable, "banned": banned})):
        with open(os.path.join(HERE, fn), "w", encoding="utf-8") as fh:
            json.dump(data, fh, indent=1, ensure_ascii=False)
            fh.write("\n")
    with open(os.path.join(HERE, "solstice_clash_wiki.txt"), "w", encoding="utf-8") as fh:
        fh.write(event_wt)

    db = os.path.join(HERE, "heroes.sqlite")
    if os.path.exists(db):
        os.remove(db)
    con = sqlite3.connect(db)
    con.executescript(SCHEMA)
    for h in heroes:
        con.execute("INSERT OR REPLACE INTO hero VALUES(?,?,?,?,?,?,?,?,?,?,?)",
                    (h["slug"], h["name"], h["faction"], h["hero_class"],
                     h["damage_type"], h["attack_range"], h["rarity"], h["title"],
                     h["gender"], h["race"], f"Hero {h['name']}.png"))
        for s in h["skins"]:
            con.execute("INSERT OR IGNORE INTO hero_skin(hero_slug,skin_name,combat_icon)"
                        " VALUES(?,?,?)", (h["slug"], s, f"Hero {s}.png"))
        for k in h["skills"]:
            con.execute(
                "INSERT OR IGNORE INTO hero_skill(hero_slug,skill_type,skill_name,"
                "attack_range,cooldown,energy,summary,detail) VALUES(?,?,?,?,?,?,?,?)",
                (h["slug"], k["type"], k["name"], k["range"], k["cd"], k["energy"],
                 k["lite"], k["full"]))
    known = {n.lower(): s for n, s in con.execute("SELECT name,slug FROM hero")}
    unlinked = []
    for u in usable:
        slug = known.get(u["name"].lower())
        if not slug:
            unlinked.append(u["name"])
        con.execute("INSERT OR REPLACE INTO solstice_roster"
                    "(name,hero_slug,faction,status,adjustment,hp_pct,atk_pct)"
                    " VALUES(?,?,?,?,?,?,?)",
                    (u["name"], slug, u["faction"], "usable",
                     u["adjustment"] or None, u["hp_pct"], u["atk_pct"]))
    for b in banned:
        con.execute("INSERT OR REPLACE INTO solstice_roster(name,hero_slug,faction,status)"
                    " VALUES(?,?,?,?)", (b, known.get(b.lower()), None, "banned"))
    con.commit()

    counts = {t: con.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
              for t in ("hero", "hero_skin", "hero_skill", "solstice_roster")}
    print("  rows:", counts)
    print("  usable per faction:", dict(Counter(u["faction"] for u in usable)))
    print("  banned:", len(banned))
    if unlinked:
        print("  WARNING unlinked roster names:", unlinked)


if __name__ == "__main__":
    main()
