#!/usr/bin/env python3
"""Rebuild the AFK Journey hero + Solstice Clash database from the Fandom wiki API.

Everything in this directory is generated by this script. Re-run it to refresh
after a balance patch or a new event rotation:

    python3 build_hero_db.py [path/to/heroes.sqlite]

Without an argument it targets the database beside this script. Generated JSON and the
wikitext snapshot are written next to whichever database is targeted.

Why the API and not the HTML: the wiki's normal pages sit behind Cloudflare
(WebFetch gets HTTP 402, agent-browser gets a "Just a moment..." challenge), but
`api.php` is not protected. No stealth browser is needed.

Why this data is trustworthy for template matching: the wiki's `File:Hero <Name>.png`
files are the datamined in-game combat icons. Rendering the in-game 96px circular
roster icon from them is a fixed transform (see ICON_SCALE / ICON_OFFSET below),
verified at 20/20 on hand-labelled Lightbearer icons and 8/8 against a 124-hero
candidate set.

Outputs (all committed):
    heroes.sqlite            hero / hero_skill / hero_skin / solstice_roster
    hero_db_full.json        parsed hero records incl. skills
    wiki_skins.json          skin -> {hero, rarity, type}
    wiki_skins_by_hero.json  hero -> [skin names]
    solstice_roster.json     event usable/banned lists with stat adjustments
    solstice_clash_wiki.txt  raw wikitext snapshot of the event page
"""

from __future__ import annotations

import datetime
import json
import os
import re
import sqlite3
import subprocess
import sys
import time
import urllib.parse
import urllib.request
from collections import Counter

API = "https://afk-journey.fandom.com/api.php"
UA = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) Chrome/146.0 Safari/537.36"}
HERE = os.path.dirname(os.path.abspath(__file__))

EVENT_PAGE = "Solstice Clash"
FACTIONS = ["Lightbearer", "Mauler", "Wilder", "Graveborn",
            "Hypogean", "Celestial", "Dimensional"]

# Transform from a wiki combat icon (180x248) to the in-game 96px circular icon.
ICON_SCALE = 0.68
ICON_OFFSET = (13, 35)   # (x, y) crop origin after scaling
ICON_MASK_RADIUS = 44


def api(**params):
    params.setdefault("format", "json")
    params.setdefault("formatversion", "2")
    req = urllib.request.Request(API + "?" + urllib.parse.urlencode(params), headers=UA)
    return json.load(urllib.request.urlopen(req, timeout=60))


def category_members(title: str) -> list[str]:
    out, cont = [], {}
    while True:
        d = api(action="query", list="categorymembers", cmtitle=title,
                cmlimit="500", **cont)
        out += [m["title"] for m in d["query"]["categorymembers"]
                if not m["title"].startswith(("Category:", "File:", "Template:"))]
        if "continue" not in d:
            return out
        cont = d["continue"]


def wikitext_for(titles: list[str], batch: int = 50) -> dict[str, str]:
    out = {}
    for i in range(0, len(titles), batch):
        d = api(action="query", titles="|".join(titles[i:i + batch]),
                prop="revisions", rvprop="content", rvslots="main")
        for pg in d["query"]["pages"]:
            try:
                out[pg["title"]] = pg["revisions"][0]["slots"]["main"]["content"]
            except (KeyError, IndexError):
                continue
        time.sleep(0.2)
    return out


def templates(wt: str, name: str) -> list[str]:
    """Extract {{name ...}} blocks, brace-balanced so nested templates survive."""
    out, i, tag = [], 0, "{{" + name
    while True:
        i = wt.find(tag, i)
        if i < 0:
            return out
        j, depth = i + 2, 1
        while j < len(wt) and depth:
            if wt.startswith("{{", j):
                depth += 1
                j += 2
            elif wt.startswith("}}", j):
                depth -= 1
                j += 2
            else:
                j += 1
        out.append(wt[i + 2:j - 2])
        i = j


def fields(block: str) -> dict[str, str]:
    """Split a template body on top-level pipes only."""
    parts, depth, cur = [], 0, ""
    for k, c in enumerate(block):
        if block.startswith("{{", k) or block.startswith("[[", k):
            depth += 1
        if block.startswith("}}", k) or block.startswith("]]", k):
            depth = max(0, depth - 1)
        if c == "|" and depth == 0:
            parts.append(cur)
            cur = ""
        else:
            cur += c
    parts.append(cur)
    out = {}
    for p in parts[1:]:
        if "=" in p:
            k, v = p.split("=", 1)
            out[k.strip()] = v.strip()
    return out


def clean(s: str | None) -> str | None:
    if not s:
        return s
    s = re.sub(r"\{\{b\|([^}]*)\}\}", r"\1", s)
    s = re.sub(r"\{\{ATK\|([^}|]*)[^}]*\}\}", r"ATK \1", s)
    s = re.sub(r"\{\{PWR\|([^}|]*)[^}]*\}\}", r"PWR \1", s)
    s = re.sub(r"\{\{[^}]*\}\}", "", s)
    s = re.sub(r"\[\[([^\]|]*\|)?([^\]]*)\]\]", r"\2", s)
    return re.sub(r"\s+", " ", s).strip()


def slugify(name: str) -> str:
    return re.sub(r"_+", "_", re.sub(r"[^a-z0-9]", "_", name.lower())).strip("_")


def build_skins() -> dict[str, dict]:
    pages = category_members("Category:Skins")
    res = {}
    for title, wt in wikitext_for(pages).items():
        def fld(n):
            m = re.search(r"\|\s*" + n + r"\s*=\s*([^\n|]+)", wt)
            return m.group(1).strip() if m else None
        res[title] = {"hero": fld("hero"), "rarity": fld("rarity"), "type": fld("type")}
    return res


def build_heroes(skins_by_hero: dict[str, list[str]]) -> list[dict]:
    pages = category_members("Category:Heroes")
    out = []
    for name, wt in wikitext_for(pages).items():
        ib = templates(wt, "Character Infobox")
        if not ib:
            continue
        f = fields("x|" + ib[0])
        skills, seen = [], set()
        for marker in ("Skill\n", "Skill|", "Skill "):
            for b in templates(wt, marker):
                g = fields("x|" + b)
                nm = g.get("name")
                if not nm or nm in seen:
                    continue
                seen.add(nm)
                skills.append({
                    "type": g.get("type"), "name": nm, "range": g.get("range"),
                    "cd": g.get("cd"), "energy": g.get("energy"),
                    "lite": clean(g.get("lite")), "full": clean(g.get("full")),
                })
        faction = f.get("faction")
        if faction and faction.startswith("<!--"):
            faction = "Lightbearer"      # wiki comment marks a factionless Lightbearer
        rng = f.get("range")
        out.append({
            "name": name, "slug": slugify(name), "faction": faction,
            "hero_class": f.get("class"), "damage_type": f.get("damage"),
            "attack_range": (re.sub(r"[^0-9]", "", rng) or None) if rng else None,
            "rarity": f.get("rarity"), "title": f.get("title"),
            "gender": f.get("gender"), "race": f.get("race"),
            "skins": skins_by_hero.get(name, []), "skills": skills,
        })
    return out


def build_event_roster(wt: str) -> tuple[list[dict], list[str]]:
    i, j = wt.find("==Usable Heroes=="), wt.find("==Banned Heroes==")
    usable = []
    parts = re.split(r"\{\{(" + "|".join(FACTIONS) + r")\}\}", wt[i:j])
    for k in range(1, len(parts), 2):
        faction, body = parts[k], parts[k + 1]
        m = (re.search(r"\{\{Card List\|mini=1\|param_delim=,\|1=(.*?)\}\}", body, re.S)
             or re.search(r"\{\{Card List\|mini=1\|(.*?)\}\}", body, re.S))
        if not m:
            continue
        raw = re.sub(r"<!--.*?-->", "", m.group(1), flags=re.S)
        for ent in raw.split(";"):
            ent = ent.strip()
            if not ent:
                continue
            cm = re.search(r"\{caption=(.*?)\}", ent)
            adj = cm.group(1).strip() if cm else ""
            nm = re.sub(r"\{caption=.*?\}", "", ent).strip()
            if not nm:
                continue
            hp = atk = None
            for pm in re.finditer(r"(HP|ATK)\s*([+-]\d+)%", adj):
                if pm.group(1) == "HP":
                    hp = int(pm.group(2))
                else:
                    atk = int(pm.group(2))
            usable.append({"faction": faction, "name": nm, "adjustment": adj,
                           "hp_pct": hp, "atk_pct": atk})
    bm = re.search(r"\{\{Card List\|mini=1\|(.*?)\}\}", wt[j:], re.S)
    banned = [b.strip() for b in
              re.sub(r"<!--.*?-->", "", bm.group(1), flags=re.S).split(";") if b.strip()]
    return usable, banned


# Schema now lives in schema.sql, applied by migrate.py.


def main() -> None:
    # Resolve the target database FIRST: the JSON/wikitext artefacts are written beside it,
    # so it must exist before anything is written.
    db = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "heroes.sqlite")

    print("fetching skins ...")
    skins = build_skins()
    by_hero: dict[str, list[str]] = {}
    for skin, v in skins.items():
        if v.get("hero"):
            by_hero.setdefault(v["hero"], []).append(skin)

    print("fetching heroes ...")
    heroes = build_heroes(by_hero)

    run_stamp = datetime.datetime.now().isoformat(timespec="seconds")

    print(f"fetching event page {EVENT_PAGE!r} ...")
    event_wt = api(action="parse", page=EVENT_PAGE, prop="wikitext")["parse"]["wikitext"]
    usable, banned = build_event_roster(event_wt)

    out_dir = os.path.dirname(os.path.abspath(db)) or HERE
    for fn, data in (("hero_db_full.json", heroes),
                     ("wiki_skins.json", skins),
                     ("wiki_skins_by_hero.json", by_hero),
                     ("solstice_roster.json", {"usable": usable, "banned": banned})):
        with open(os.path.join(out_dir, fn), "w", encoding="utf-8") as fh:
            json.dump(data, fh, indent=1, ensure_ascii=False)
            fh.write("\n")
    with open(os.path.join(out_dir, "solstice_clash_wiki.txt"), "w", encoding="utf-8") as fh:
        fh.write(event_wt)

    # db was resolved at the top of main(). Optional argv[1] lets tests target a temp copy;
    # without it a test "pointing at a temp copy" via cwd would silently rewrite the shipped
    # database and then assert on the untouched copy - passing trivially.
    # NON-DESTRUCTIVE. This script refreshes only the wiki-derived tables. Locally
    # earned data - hero.external_id / game_icon, hero_alias, cell_registry,
    # art_transform, library_config - is measured here and CANNOT be rebuilt from the
    # wiki, so it must survive a refresh. Deleting the file would destroy all of it.
    subprocess.run([sys.executable, os.path.join(HERE, "migrate.py"), db], check=True)
    con = sqlite3.connect(db)
    # preserve the icon mapping across the refresh
    preserved = {
        name: (ext, gicon, wicon)
        for name, ext, gicon, wicon in con.execute(
            "SELECT name, external_id, game_icon, wiki_icon FROM hero "
            "WHERE external_id IS NOT NULL OR game_icon IS NOT NULL OR wiki_icon IS NOT NULL")
    }
    # Keyed by (hero_slug, skin_name) because that is the table's uniqueness. Keying on
    # skin_name alone collapses rows when two heroes share a skin name, and the restore
    # would then write one hero's icons onto the other's row.
    preserved_skin = {
        (hs, sk): (g, w, iw, ih) for hs, sk, g, w, iw, ih in con.execute(
            "SELECT hero_slug, skin_name, game_icon, wiki_icon, icon_w, icon_h FROM hero_skin "
            "WHERE game_icon IS NOT NULL OR wiki_icon IS NOT NULL "
            "OR icon_w IS NOT NULL OR icon_h IS NOT NULL")
    }
    # hero_skill and solstice_roster hold NOTHING locally earned, so a clean rebuild is
    # correct for them. hero_skin does (game_icon/wiki_icon/icon_w/icon_h), so it is upserted
    # and stamped instead - a transient wiki omission must not delete a measured icon.
    con.execute("DELETE FROM hero_skill")
    con.execute("DELETE FROM solstice_roster")
    for h in heroes:
        # Named columns, never positional: the table has grown and a positional
        # INSERT silently breaks (or loudly, as it did) whenever a column is added.
        # INSERT OR REPLACE would also null out preserved columns, so upsert instead.
        con.execute(
            "INSERT INTO hero(slug,name,faction,hero_class,damage_type,attack_range,"
            "rarity,title,gender,race) VALUES(?,?,?,?,?,?,?,?,?,?) "
            "ON CONFLICT(slug) DO UPDATE SET name=excluded.name, faction=excluded.faction,"
            "hero_class=excluded.hero_class, damage_type=excluded.damage_type,"
            "attack_range=excluded.attack_range, rarity=excluded.rarity, title=excluded.title,"
            "gender=excluded.gender, race=excluded.race",
            (h["slug"], h["name"], h["faction"], h["hero_class"],
             h["damage_type"], h["attack_range"], h["rarity"], h["title"],
             h["gender"], h["race"]))
        con.execute("UPDATE hero SET last_seen=? WHERE slug=?", (run_stamp, h["slug"]))
        for s in h["skins"]:
            con.execute("INSERT INTO hero_skin(hero_slug,skin_name,last_seen) VALUES(?,?,?) "
                        "ON CONFLICT(hero_slug,skin_name) DO UPDATE SET last_seen=excluded.last_seen",
                        (h["slug"], s, run_stamp))
        for k in h["skills"]:
            con.execute(
                "INSERT OR IGNORE INTO hero_skill(hero_slug,skill_type,skill_name,"
                "attack_range,cooldown,energy,summary,detail) VALUES(?,?,?,?,?,?,?,?)",
                (h["slug"], k["type"], k["name"], k["range"], k["cd"], k["energy"],
                 k["lite"], k["full"]))
    restored = 0
    for name, (ext, gicon, wicon) in preserved.items():
        restored += con.execute(
            "UPDATE hero SET external_id=?, game_icon=?, wiki_icon=? WHERE name=?",
            (ext, gicon, wicon, name)).rowcount

    for (hs, sk), (g, w, iw, ih) in preserved_skin.items():
        con.execute("UPDATE hero_skin SET game_icon=?, wiki_icon=?, icon_w=?, icon_h=? "
                    "WHERE hero_slug=? AND skin_name=?", (g, w, iw, ih, hs, sk))

    known = {n.lower(): s for n, s in con.execute("SELECT name,slug FROM hero")}
    unlinked = []
    for u in usable:
        slug = known.get(u["name"].lower())
        if not slug:
            unlinked.append(u["name"])
        con.execute("INSERT OR REPLACE INTO solstice_roster"
                    "(name,hero_slug,faction,status,adjustment,hp_pct,atk_pct)"
                    " VALUES(?,?,?,?,?,?,?)",
                    (u["name"], slug, u["faction"], "usable",
                     u["adjustment"] or None, u["hp_pct"], u["atk_pct"]))
    # A hero can appear in BOTH lists on the wiki (Zorya does). Usable wins: she is
    # playable and gets picked in real matches. Using INSERT OR REPLACE here would let
    # the banned row clobber the usable one and silently drop her from the roster.
    usable_names = {u["name"].lower() for u in usable}
    for b in banned:
        if b.lower() in usable_names:
            print(f"  note: {b!r} listed as both usable and banned - keeping usable")
            continue
        con.execute("INSERT OR REPLACE INTO solstice_roster(name,hero_slug,faction,status)"
                    " VALUES(?,?,?,?)", (b, known.get(b.lower()), None, "banned"))
    con.commit()

    stale_skins = [f"{hs}/{sk}" for hs, sk in con.execute(
        "SELECT hero_slug, skin_name FROM hero_skin WHERE last_seen IS NULL OR last_seen <> ?",
        (run_stamp,))]
    if stale_skins:
        print(f"  WARNING: {len(stale_skins)} skin rows absent from this wiki fetch "
              f"(kept, not deleted): {stale_skins[:8]}{' ...' if len(stale_skins) > 8 else ''}")
    stale = [n for (n,) in con.execute(
        "SELECT name FROM hero WHERE last_seen IS NULL OR last_seen <> ?", (run_stamp,))]
    if stale:
        print(f"  WARNING: {len(stale)} hero rows absent from this wiki fetch "
              f"(kept, not deleted - they may carry a game icon mapping):")
        print(f"           {stale[:12]}{' ...' if len(stale) > 12 else ''}")
    print(f"  icon mappings preserved: {restored}/{len(preserved)}")
    counts = {t: con.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
              for t in ("hero", "hero_skin", "hero_skill", "solstice_roster",
                        "hero_alias", "cell_registry", "art_transform")}
    print("  rows:", counts)
    print("  usable per faction:", dict(Counter(u["faction"] for u in usable)))
    print("  banned:", len(banned))
    if unlinked:
        print("  WARNING unlinked roster names:", unlinked)


if __name__ == "__main__":
    main()
